sonar.projectKey=abdelilah771_Pulse
sonar.organization=abdelilah771

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Pulse Next.js App
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

# Excludes files from coverage analysis
sonar.exclusions=node_modules/**, .next/**, out/**, dist/**, **/*.css, **/*.config.js, **/*.config.ts

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
